"""Constants ported from agent-trace-redaction-methodology."""
from __future__ import annotations

SENSITIVE_FIELD_EXACT = {
    "authorization",
    "cookie",
    "setcookie",
    "password",
    "passwd",
    "secret",
    "token",
    "apikey",
    "api_key",
    "accesskey",
    "access_key",
    "privatekey",
    "private_key",
    "credential",
    "credentials",
    "encryptedcontent",
    "encrypted_content",
    "thinkingsignature",
    "thinking_signature",
    "signature",
    "shareurl",
    "share_url",
}

SENSITIVE_FIELD_SUBSTRINGS = (
    "api_key",
    "apikey",
    "authorization",
    "bearer",
    "credential",
    "encrypted_content",
    "encryptedcontent",
    "password",
    "private_key",
    "privatekey",
    "refresh_token",
    "secret",
    "session_secret",
    "share_url",
    "shareurl",
    "thinking_signature",
    "thinkingsignature",
)

PRIVATE_TERM_DENYLIST = {
    "admin",
    "agent",
    "assets",
    "benchmark",
    "checker",
    "cloud",
    "codex",
    "dev",
    "downloads",
    "engine",
    "github.com",
    "home",
    "localhost",
    "proxy",
    "redacted",
    "redaction",
    "setup",
    "sync",
    "test",
    "throughput",
    "trace",
    "traces",
    "user",
    "videos",
    "work",
}

DEFAULT_PUBLIC_URL_ALLOWLIST = {
    "github.com",
    "raw.githubusercontent.com",
    "gist.github.com",
    "docs.github.com",
    "npmjs.com",
    "www.npmjs.com",
    "registry.npmjs.org",
    "pypi.org",
    "files.pythonhosted.org",
    "python.org",
    "docs.python.org",
    "nodejs.org",
    "developer.mozilla.org",
}
